apiVersion: v2
appVersion: '1.0'
description: A Helm chart for hwf-staffapp App
name: help-with-fees-staffapp
home: https://github.com/hmcts/hwf-staffapp
version: 0.0.78
dependencies:
  - name: base
    version: 1.3.0
    repository: 'https://hmctspublic.azurecr.io/helm/v1/repo/'
